// @ts-check
// The sidebar is fully autogenerated from the docs/ tree:
//   - docs/intro.md            -> top "Overview" entry (sidebar_position: 1)
//   - docs/<Repo>/             -> one section per source repo
//   - docs/<Repo>/README.md    -> automatically used as that section's index page
//                                 (so it is NOT duplicated as a child link)
//
// Section label + order come from docs/<Repo>/_category_.json. Those files are OWNED by
// this repo and PRESERVED by the doc-sync (see scripts/sync-docs.sh and the workflow
// template), so syncing a source repo's docs never clobbers the section title/position.
//
// Result: contributors in source repos just edit markdown; layout is controlled here.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
